### ISSUE TITLE
Relaxed click requirements allow click 7, which does not work

### ISSUE THREAD

**Issue by Flameeyes** [rytilahti/python-songpal#103]
Using `pip install .` does not force a `click` update to 8 after b7dbe8fedb39ea8583997f68d941035277d09ede which then fails at runtime with:

```
(venv) flameeyes@seleya:~/devel/repos/python-songpal> songpal --endpoint http://192.168.85.188:10000/sony --help
Traceback (most recent call last):
  File "/home/flameeyes/devel/repos/hassio-core/venv/bin/songpal", line 5, in <module>
    from songpal.main import cli
  File "/home/flameeyes/devel/repos/hassio-core/venv/lib64/python3.9/site-packages/songpal/main.py", line 116, in <module>
    async def cli(ctx, endpoint, debug, websocket, post):
  File "/home/flameeyes/devel/repos/hassio-core/venv/lib64/python3.9/site-packages/click/decorators.py", line 304, in decorator
    return option(*(param_decls or ("--version",)), **attrs)(f)
  File "/home/flameeyes/devel/repos/hassio-core/venv/lib64/python3.9/site-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/flameeyes/devel/repos/hassio-core/venv/lib64/python3.9/site-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'package_name'
```

**Comment by rytilahti** [comment]
I just created a PR for that, I don't think it's worth trying to maintain compat with click7 at this point, if someone really wants to have it they are free to submit a PR to change that :-)
