### ISSUE TITLE
SRS-X88:  'unsupported operation'

### ISSUE THREAD

**Issue by Yuke-hd** [rytilahti/python-songpal#149]
Was working fine for years pre homeassitant 2024 releases
Here are some logs

Regards

```
x511:/config#  songpal  --endpoint http://192.168.0.174:54480/sony command avContent getAvailablePlaybackFunction {}
Calling avContent.getAvailablePlaybackFunction with params {}
INFO:songpal.device:Calling avContent.getAvailablePlaybackFunction({})
Error: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation


x511:/config#  songpal  --endpoint http://192.168.0.174:54480/sony status
Power on
Volume: 13/61
Not playing any media
Error: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation

x511:/config#  songpal --debug  --endpoint http://192.168.0.174:54480/sony command avContent getAvailablePlaybackFunction {}
Setting debug level to 1
DEBUG:root:Using endpoint http://192.168.0.174:54480/sony
DEBUG:songpal.device:Endpoint: http://192.168.0.174:54480/sony
DEBUG:songpal.device:Guide endpoint: http://192.168.0.174:54480/sony/guide
DEBUG:songpal.device:Got 4 services!
DEBUG:songpal.service:Available protocols for audio: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyVolumeInformation', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyVolumeInformation, versions=[{'version': '1.0'}], endpoint=http://192.168.0.174:54480/sony/audio>]
DEBUG:songpal.service:Available protocols for avContent: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyAvailablePlaybackFunction', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifyPlayingContentInfo',
 'versions': [{'authLevel': 'private', 'version': '1.0'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyAvailablePlaybackFunction, versions=[{'version': '1.0'}], endpoint=http://192.168.0.174:54480/sony/avContent>, <Notification notifyPlayingContentInfo, versions=[{'authLevel': 'private', 'version': '1.0'}], endpoint=http://192.168.0.174:54480/sony/avContent>]
DEBUG:songpal.service:Available protocols for guide: ['xhrpost:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.XHRPost
DEBUG:songpal.service:Available protocols for system: ['xhrpost:jsonizer', 'websocket:jsonizer']
DEBUG:songpal.service:Using protocol: ProtocolType.WebSocket
DEBUG:songpal.notification:notification payload: {'name': 'notifyPowerStatus', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifySWUpdateInfo', 'versions': [{'version': '1.0'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifySettingsUpdate', 'versions': [{'version': '1.1'}]}
DEBUG:songpal.notification:notification payload: {'name': 'notifyStorageStatus',
 'versions': [{'authLevel': 'generic', 'version': '1.1'}]}
DEBUG:songpal.service:Got notifications: [<Notification notifyPowerStatus, versions=[{'version': '1.0'}], endpoint=http://192.168.0.174:54480/sony/system>, <Notification notifySWUpdateInfo, versions=[{'version': '1.0'}], endpoint=http://192.168.0.174:54480/sony/system>, <Notification notifySettingsUpdate, versions=[{'version': '1.1'}], endpoint=http://192.168.0.174:54480/sony/system>, <Notification notifyStorageStatus, versions=[{'authLevel': 'generic', 'version': '1.1'}], endpoint=http://192.168.0.174:54480/sony/system>]
Calling avContent.getAvailablePlaybackFunction with params {}
INFO:songpal.device:Calling avContent.getAvailablePlaybackFunction({})
DEBUG:songpal.service:getAvailablePlaybackFunction version 1.0 got called with args (({},)) kwargs ({})
DEBUG:songpal.method:<Method avContent.getAvailablePlaybackFunction({'output': <class 'str'>}) -> {'functions': 'FunctionInfo[]', 'output': <class 'str'>, 'uri': <class 'str'>} version 1.0>
Error: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation
Traceback (most recent call last):
  File "/usr/local/bin/songpal", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/songpal/main.py", line 59, in wrapper
    raise ex
  File "/usr/local/lib/python3.11/site-packages/songpal/main.py", line 50, in wrapper
    return loop.run_until_complete(f(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/songpal/main.py", line 628, in command
    res = await dev.raw_command(service, method, params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/songpal/device.py", line 567, in raw_command
    return await self.services[service][method](params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/songpal/method.py", line 136, in __call__
    raise SongpalException(
songpal.common.SongpalException: Got an error for getAvailablePlaybackFunction: [15, 'unsupported operation']: UnsupportedOperation (15): unsupported operation
```

**Comment by Yuke-hd** [comment]
Possible clues: I opened the sony Music Center app on my phone and clicked through a couple input sources then it all starts to work

**Comment by rytilahti** [comment]
Ping @allistermaguire

**Comment by allistermaguire** [comment]
Hi @Yuke-hd, sorry for the issue. I just have a couple of questions to try and diagnose the issue.
1. What version of Hass are you running?
2. What version of Hass were you running before you encountered this issue? Version `2023.12.0` included significant changes with `0.16.0`, and `2024.2.0` includes a fix with `0.16.1` for a similar issue encountered by the SRS-X77.
3. Can you please run the following and send through the output? You will want to attach the last one as a file.
```
songpal  --version
```
```
songpal  --debug --endpoint http://192.168.0.174:54480/sony input
```
```
songpal  --endpoint http://192.168.0.174:54480/sony dump-devinfo
```

Thanks Allister

**Comment by Yuke-hd** [comment]
Hi @allistermaguire 

1. I'm currently on 2024.1.6 
2. I can remember, sorry
3. see [host.txt](https://github.com/rytilahti/python-songpal/files/14302855/host.txt) and [hassdocker.txt](https://github.com/rytilahti/python-songpal/files/14302881/hassdocker.txt)

**Comment by Yuke-hd** [comment]
Maybe i need to edit the title, just realised 0.16 also has this issue

**Comment by allistermaguire** [comment]
Thanks for the information @Yuke-hd

Both of those outputs for `songpal input` look fine without error, on both `0.16.0` and `0.16.1` The error that you were receiving with `songpal status` was at the point where it effectively calls `get_inputs()`. So that is unexpected. Maybe it goes to your comment that selecting an input in the Music Center app. My guess is that unless an input is selected it returns `UnsupportedOperation (15)`.

You can see here that it is returning `dlna:music`
```
DEBUG:songpal.service:getAvailablePlaybackFunction version 1.0 got called with args (()) kwargs ({'output': ''})
DEBUG:songpal.method:got res: {'id': 6, 'result': [[{'functions': [], 'uri': 'dlna:music'}]]}
```

Based on the information you provided, I would have expected it to be broken with `0.16.0` as `getAvailablePlaybackFunction` is always called. But in `0.16.1` I have updated it to only be called if `getCurrentExternalTerminalsStatus` is version `1.2`, and the SRS-X88 uses version `1.0` and therefore it would not be called and you will not receive an error.

With version `0.16.1` `getAvailablePlaybackFunction` being broken (sometimes) for your device shouldn't matter, as it won't be called. To get version `0.16.1` in Home Assistant, you will need to upgrade to version `2024.2.0` or higher.

**Comment by Yuke-hd** [comment]
Thanks, I will update Hass and see how it goes

**Comment by allistermaguire** [comment]
No problem. I would have like it to be more definitive with the testing; not working in `0.16.0` and working in `0.16.1`. But I am confident that you should be good with the newer version in Hass `2024.2.0` and above. They must be close to releasing version `2024.2.2`.

**Comment by rytilahti** [comment]
Any updates on this, @Yuke-hd?

**Comment by Yuke-hd** [comment]
Hey @rytilahti sorry for the late reply, it work perfectly after updating
