### ISSUE TITLE
Error when trying to run song pal after installation in venv

### ISSUE THREAD

**Issue by apateluk** [rytilahti/python-songpal#20]
Have installed song pal using the pip install method listed on the homepage, but receive this error :

`homeassistant@hassio:/srv $ source /srv/homeassistant/bin/activate
(homeassistant) homeassistant@hassio:/srv $ songpal
songpal
(homeassistant) homeassistant@hassio:/srv $ songpal discover
Traceback (most recent call last):
  File "/srv/homeassistant/bin/songpal", line 7, in <module>
    from songpal.main import cli
  File "/srv/homeassistant/lib/python3.5/site-packages/songpal/main.py", line 10, in <module>
    import upnpclient
  File "/srv/homeassistant/lib/python3.5/site-packages/upnpclient/__init__.py", line 143, in <module>
    from upnpclient import const, errors, marshal, soap, ssdp, upnp, util  # noqa: F401
  File "/srv/homeassistant/lib/python3.5/site-packages/upnpclient/soap.py", line 4, in <module>
    from lxml import etree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
(homeassistant) homeassistant@hassio:/srv $ `

**Comment by rytilahti** [comment]
Try installing `libxslt1.1` (or similar) package, that should do the trick.

**Comment by apateluk** [comment]
That did it thanks. I assumed using the pip method would in all dependencies.
