### ISSUE TITLE
ModuleNotFoundError: No module named 'async_upnp_client.search

### ISSUE THREAD

**Issue by ABrauser** [rytilahti/python-songpal#51]
Hello I have updated to the latest version by the command:

`pip install python-songpal --upgrade  `

It updated properly but i now receiving the following errors.

```PS C:\Users\Sauerkraut> songpal discover                                                                                  Traceback (most recent call last):
  File "c:\users\Sauerkraut\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\Sauerkraut\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sauerkraut\AppData\Local\Programs\Python\Python37\Scripts\songpal.exe\__main__.py", line 5, in <module>
  File "c:\users\Sauerkraut\appdata\local\programs\python\python37\lib\site-packages\songpal\main.py", line 15, in <module>
    from songpal.discovery import Discover
  File "c:\users\Sauerkraut\appdata\local\programs\python\python37\lib\site-packages\songpal\discovery.py", line 2, in <module>
    from async_upnp_client.search import async_search
ModuleNotFoundError: No module named 'async_upnp_client.search'
PS C:\Users\Sauerkraut>      ```

the version before worked without Problem. Do you know whats the issue?

**Comment by rytilahti** [comment]
Did you already try to update `async_upnp_client`? Its search module was changed last time in January and the search module has existed long before that. What does `pip show async_upnp_client` show for the version?

Also, what does happen if you open python interpreter and try to import it manually?
```
$ python
>>> import async_upnp_client.search
```
or even `import async_upnp_client` and then doing `print(dir(async_upnp_client))` to see which modules are available.

**Comment by rytilahti** [comment]
Closing for inactivity, please reopen if this is still an issue, thanks!
