### ISSUE TITLE
TypeError: attrib() got an unexpected keyword argument 'convert'

### ISSUE THREAD

**Issue by tenfire** [rytilahti/python-songpal#54]
I get an error when loading songpal component in HomeAssistant. After some googling i found the same problem in other projects. Seems like `convert` is depricated and that `converter` should be used instead.

```
2019-10-06 08:47:56 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform songpal
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/src/homeassistant/homeassistant/components/songpal/media_player.py", line 63, in async_setup_platform
    from songpal import SongpalException
  File "/usr/local/lib/python3.7/site-packages/songpal/__init__.py", line 3, in <module>
    from songpal.device import Device
  File "/usr/local/lib/python3.7/site-packages/songpal/device.py", line 31, in <module>
    from songpal.notification import Notification, ConnectChange
  File "/usr/local/lib/python3.7/site-packages/songpal/notification.py", line 69, in <module>
    class SoftwareUpdateChange(ChangeNotification):
  File "/usr/local/lib/python3.7/site-packages/songpal/notification.py", line 77, in SoftwareUpdateChange
    isUpdatable = attr.ib(convert=convert_to_bool)
TypeError: attrib() got an unexpected keyword argument 'convert'
```

**Comment by dennis84de** [comment]
I am getting the same error.

I changed the "convert" to "converter" under SoftwareUpdateChange() for testing and it seems that songpal is working again.

But I don't know yet if there are side effects or something like that.

**Comment by rytilahti** [comment]
I just released a new version which fixes this, thanks for reminding me.
